version: '3.8'

services:
  voice_clone_server:
    build:
      context: .
      dockerfile: Dockerfile.voice_clone_server
    ports:
      - "5008:5008"
    environment:
      - COQUI_TOS_AGREED=1
      - COQUI_DISABLE_TOS_PROMPT=1
    #restart: unless-stopped

  tts_server:
      build:
        context: ./tts_server
        dockerfile: Dockerfile
      ports:
        - "5006:5005"
      environment:
        COQUI_TOS_AGREED: "1"
        COQUI_DISABLE_TOS_PROMPT: "1"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=gemma2:2b
      - XTTS_SERVER_URL=http://voice_clone_server:5005
      - VOICE_CLONE_URL=http://voice_clone_server:5008/synthesize_meditation
      - RECIPE_TTS_URL=http://tts_server:5005/speak
    restart: unless-stopped
